---
trigger: none

name: $(Date:yyyyMMdd).$(Rev:r)_${{ parameters.subscription }}

pool:
  vmImage: windows-latest

parameters:
  - name: subscription
    displayName: Subscription
    type: string
    default: UK Advisory Dev Test
    values:
      - UK Advisory Dev Test
      - UK Advisory Prod 1
  - name: environment
    displayName: Target Environment
    type: string
    default: Dev
    values:
      - Dev
      - prod
  - name: initialDeployment
    displayName: Initial deployment
    type: boolean
    default: false

variables:
  - group: Advisory_Platform_${{parameters.environment}}

stages:
  - stage: Deploy
    displayName: Deploy ${{ parameters.subscription }}
    jobs:
      - deployment: Deploy
        displayName: Deployment to ${{ parameters.subscription }}
        environment: Advisory_DataAnalytics_Platform
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  displayName: Validate Deployment
                  inputs:
                    connectedServiceNameARM: ${{ parameters.subscription }}
                    ScriptType: InlineScript
                    azurePowerShellVersion: LatestVersion
                    Inline: |
                      $parameters = @{
                      TemplateParameterObject = @{
                        environment = "$(environment)" 
                        SubnetId = "$(SubnetId)"
                        adminLogin = "$(adminLogin)"
                        adminPassword = "$(adminPassword)"
                        ADLS_Name = "$(ADLS_Name)"
                        storage_sku = "$(storage_sku)"
                        ADLS_PE_Blob = "$(ADLS_PE_Blob)"
                        ADLS_PE_dfs = "$(ADLS_PE_dfs)"
                        SA_Name = "$(SA_Name)"
                        SA_PE_Blob = "$(SA_PE_Blob)"
                        Vault_Name = "$(Vault_Name)"
                        vaultStorageRedundancy = "$(vaultStorageRedundancy)"
                        Keyvault_Name = "$(Keyvault_Name)"
                        Datafactory_Name = "$(Datafactory_Name)"
                        integrated_runtime_name = "$(integrated_runtime_name)"
                        backup_pipeline = "$(backup_pipeline)"
                        sqlServerName = "$(sqlServerName)"
                        Server_PE_sql = "$(Server_PE_sql)"
                        workspaceName = "$(workspaceName)"
                        privateEndpointSubnetCidr = "$(privateEndpointSubnetCidr)"
                        privateSubnetCidr = "$(privateSubnetCidr)"
                        publicSubnetCidr = "$(publicSubnetCidr)"
                        vnetCidr = "$(vnetCidr)"
                        vnetNameDbks = "$(vnetNameDbks)"
                        Dbks_NSG_Name = "$(Dbks_NSG_Name)"
                       }          
                       ResourceGroupName = "$(resourceGroupName)"  
                       TemplateFile = "main.bicep"
                      }
                      Test-AzResourceGroupDeployment @parameters

                - task: AzurePowerShell@5
                  displayName: Deployment
                  condition: ${{ eq(parameters.initialDeployment, 'true')}}
                  inputs:
                    connectedServiceNameARM: ${{ parameters.subscription }}
                    ScriptType: InlineScript
                    azurePowerShellVersion: LatestVersion
                    Inline: |
                      $parameters = @{
                      TemplateParameterObject = @{
                        environment = "$(environment)"
                        SubnetId = "$(SubnetId)"
                        adminLogin = "$(adminLogin)"
                        adminPassword = "$(adminPassword)"
                        ADLS_Name = "$(ADLS_Name)"
                        storage_sku = "$(storage_sku)"
                        ADLS_PE_Blob = "$(ADLS_PE_Blob)"
                        ADLS_PE_dfs = "$(ADLS_PE_dfs)"
                        SA_Name = "$(SA_Name)"
                        SA_PE_Blob = "$(SA_PE_Blob)"
                        Vault_Name = "$(Vault_Name)"
                        vaultStorageRedundancy = "$(vaultStorageRedundancy)"  
                        Keyvault_Name = "$(Keyvault_Name)"
                        Datafactory_Name = "$(Datafactory_Name)"
                        integrated_runtime_name = "$(integrated_runtime_name)"
                        backup_pipeline = "$(backup_pipeline)"
                        sqlServerName = "$(sqlServerName)"
                        Server_PE_sql = "$(Server_PE_sql)"
                        workspaceName = "$(workspaceName)"
                        privateEndpointSubnetCidr = "$(privateEndpointSubnetCidr)"
                        privateSubnetCidr = "$(privateSubnetCidr)"
                        publicSubnetCidr = "$(publicSubnetCidr)"
                        vnetCidr = "$(vnetCidr)"
                        vnetNameDbks = "$(vnetNameDbks)"
                        Dbks_NSG_Name = "$(Dbks_NSG_Name)" 
                        }
                        ResourceGroupName = "$(resourceGroupName)"
                        TemplateFile = "main.bicep"
                      }
                      New-AzResourceGroupDeployment @parameters