parameters:
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: agentPool
    default: ""
  - name: serviceConnection
    default: ""
  - name: environmentLowerCase
    default: ""

jobs:
  #- template: ../../core/yaml/bicep-deploy.yml
  #  parameters:
  #    templatePath: "../bicep/virtual-network.bicep"
  #    displayName: "Deploy Virtual Network"
  #    deploymentName: "DeployVirtualNetwork"
  #    dependsOn: []
  #    resourceGroupName: "$(resourceGroup)"
  #    environment: "${{ parameters.environment }}"
  #    serviceConnection: "${{ parameters.serviceConnection }}"
  #    environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
  #    deploymentParameters: 
  #      virtualNetwork_name='my_vnet'
  #      subnet_name='my_subnet'

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/keyvault.bicep"
      displayName: "Deploy Keyvault"
      deploymentName: "DeployKeyvault"
      dependsOn: []
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters: 
        keyvault_name='$(keyvault_name)'
        subnet_id='$(subnet_id)'

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/storageAccount.bicep"
      displayName: "Deploy ADLS Storage Account"
      deploymentName: "DeployADLS"
      dependsOn: [DeployKeyvault]
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters:
        storageaccount_name='$(storageAccount_name)'
        storageaccount_sku='$(storageAccount_sku)'
        keyvault_name='$(keyvault_name)'
        container_names='["adf-pipeline-logs"]'
        ctrl_lifeCycleManagement=true
        isHnsEnabled=true

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/storageAccount.bicep"
      displayName: "Deploy Backup Storage Account"
      deploymentName: "DeployBackupStorage"
      dependsOn: [DeployKeyvault]
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters:
        storageaccount_name='$(storageAccountBackup_name)'
        storageaccount_sku='$(storageAccount_sku)'
        keyvault_name='$(keyvault_name)'
        container_names='["Archive"]'
        ctrl_lifeCycleManagement=false

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/datafactory.bicep"
      displayName: "Deploy Data Factory"
      deploymentName: "DeployDataFactory"
      dependsOn: [DeployADLS]
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters:
        environment="${{ parameters.environment }}"
        datafactory_name='$(dataFactory_name)'
        keyvault_name='$(keyvault_name)'
        integratedRuntime_name="integratedRuntime_name"
        repositoryName="Framework"
        repositoryType="FactoryGitHubConfiguration"
        repositoryAccountName="chixvio"
        repositoryProjectName="Pylonegg"
        repositoryCollaborationBranch="develop"
        repositoryRootFolder="src/azure.datafactory"

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/rbac.bicep"
      displayName: "Assign RBAC"
      deploymentName: "AssignRBAC"
      dependsOn: [DeployDataFactory]
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters:
        storageaccount_name='$(storageAccount_name)'
        storageaccountBackup_name='$(storageAccountBackup_name)'
        datafactory_name='$(dataFactory_name)'

#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Databricks Workspace Deployment"
#      deploymentName: "DeployDatabricksWorkspace"
#      dependsOn: [DeployStorageAccount]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/databricks.bicep"
#      deploymentParameters:
#        databricksWorkspaceName="$(databricksWorkspace_name)"
#        pricingTier="premium"

#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      templatePath: "../bicep/resourceGroup-lock.bicep"
#      displayName: "Resource Group Lock"
#      deploymentName: "ResourceGroupLock"
#      dependsOn: [DeployDataFactory]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      deploymentParameters:
