parameters:
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: agentPool
    default: ""
  - name: serviceConnection
    default: ""
  - name: environmentLowerCase
    default: ""

jobs:
#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Keyvault Deployment"
#      deploymentName: "DeployKeyvault"
#      dependsOn: []
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/keyvault.bicep"
#      deploymentParameters: 
#        keyVaultName='$(keyVaultName)'
      
#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Storage Account Deployment"
#      deploymentName: "DeployStorageAccount"
#      dependsOn: [DeployKeyvault]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/storage-account.bicep"
#      deploymentParameters:
#        networkIsolationMode='vNet'
#        keyVaultName='$(keyVaultName)'
#        storageAccountName='$(storageAccountName)'
#        ctrlDeployStreaming='false'
#        containerNames="('raw', 'curated')"

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      displayName: "Data Factory Deployment"
      deploymentName: "DeployDataFactory"
      dependsOn: [] # DeployStorageAccount
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      templatePath: "../bicep/DataFactory.bicep"
      deploymentParameters:
        environment="${{ parameters.environment }}"
        datafactory_name="$(dataFactoryName)"
        datafactory_location= "uk south"
        integrated_runtime_name="integrated_runtime_name"
        repositoryName="Advisory_DataAnalytics_Platform"
        repositoryType="FactoryVSTSConfiguration"
        repositoryAccountName="chixvio"
        repositoryProjectName="Pylonegg"
        repositoryCollaborationBranch="develop"
        repositoryRootFolder="src/azure.datafactory"

#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Databricks Workspace Deployment"
#      deploymentName: "DeployDatabricksWorkspace"
#      dependsOn: [DeployStorageAccount]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/databricks.bicep"
#      deploymentParameters:
#        databricksWorkspaceName="$(databricksWorkspaceName)"
#        pricingTier="premium"
#
