parameters:
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: agentPool
    default: ""
  - name: serviceConnection
    default: ""
  - name: environmentLowerCase
    default: ""

jobs:
  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/virtual-network.bicep"
      displayName: "Deploy Virtual Network"
      deploymentName: "DeployVirtualNetwork"
      dependsOn: []
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters: 
        virtualNetwork_name='my_vnet'
        subnet_name='my_subnet'

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/keyvault.bicep"
      displayName: "Deploy Keyvault"
      deploymentName: "DeployKeyvault"
      dependsOn: [DeployVirtualNetwork]
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters: 
        keyvault_name='$(keyvault_name)'
        subnet_id='$(subnet_id)'
      
#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Storage Account Deployment"
#      deploymentName: "DeployStorageAccount"
#      dependsOn: [DeployKeyvault]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/storage-account.bicep"
#      deploymentParameters:
#        networkIsolationMode='vNet'
#        keyVaultName='$(keyVaultName)'
#        storageAccountName='$(storageAccountName)'
#        ctrlDeployStreaming='false'
#        containerNames="('raw', 'curated')"

  - template: ../../core/yaml/bicep-deploy.yml
    parameters:
      templatePath: "../bicep/datafactory.bicep"
      displayName: "Deploy Data Factory"
      deploymentName: "DeployDataFactory"
      dependsOn: [DeployKeyvault] # DeployStorageAccount
      resourceGroupName: "$(resourceGroup)"
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      deploymentParameters:
        environment="${{ parameters.environment }}"
        datafactory_name="$(dataFactoryName)"
        keyvault_name='$(keyvault_name)'
        integrated_runtime_name="integrated_runtime_name"
        repositoryName="Framework"
        repositoryType="FactoryGitHubConfiguration"
        repositoryAccountName="chixvio"
        repositoryProjectName="Pylonegg"
        repositoryCollaborationBranch="develop"
        repositoryRootFolder="src/azure.datafactory"

#  - template: ../../core/yaml/bicep-deploy.yml
#    parameters:
#      displayName: "Databricks Workspace Deployment"
#      deploymentName: "DeployDatabricksWorkspace"
#      dependsOn: [DeployStorageAccount]
#      resourceGroupName: "$(resourceGroup)"
#      environment: "${{ parameters.environment }}"
#      serviceConnection: "${{ parameters.serviceConnection }}"
#      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
#      templatePath: "../bicep/databricks.bicep"
#      deploymentParameters:
#        databricksWorkspaceName="$(databricksWorkspaceName)"
#        pricingTier="premium"
#