stages:
- stage: Development
  variables:
    - group: "Dev"
  jobs:
  - job: Development
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: "Pylonegg - Dev"
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Getting access token..."
          DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" -o tsv)
          echo "##vso[task.setvariable variable=DATABRICKS_TOKEN]$DATABRICKS_TOKEN"
        
    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)/src/azure.databricks/databricks-setup.ps1
        arguments: >
          -DatabricksHost "$(DATABRICKS_HOST)"
          -DatabricksToken "$(DATABRICKS_TOKEN)"
          -ClusterName "POC Cluster"
          -Environment "$(env)"
      displayName: 'Deploy Databricks'