parameters:
- name: buildTemplatePath
  default: ''
- name: deployTemplatePath
  default: ''


stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: ${{ parameters.buildTemplatePath }}
        parameters:
         serviceConnection: "Pylonegg - Dev"

  - stage: DEV
    displayName: DEV
    dependsOn: [Build]
    jobs:
      - template: "${{ parameters.deployTemplatePath }}"
        parameters:
          environment: "Dev"
          serviceConnection: "Pylonegg - Dev"
          environmentVariableGroup: "Dev"
          environmentLowerCase: dev