parameters:
  - name: deploymentName
    default: ""
  - name: serviceConnection
    default: ""
  - name: filePath
    default: ""
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: dependsOn
    type: object
    default: []
  - name: displayName
    default: ""
  - name: deploymentParameters
    default: ""


jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: ${{parameters.displayName}}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - group: ${{ parameters.environmentVariableGroup }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop

            # Deploy ADF
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Data Factory Artifacts'
              inputs:
                deploymentName: 'PublishADF'
                deploymentScope: 'Resource Group'
                resourceGroupName: '$(ResourceGroupName)'
                azureResourceManagerConnection: ${{ parameters.serviceConnection }}
                templateLocation: 'Linked artifact'
                location: 'West Europe' # Update <<===================
                csmFile: '$(Pipeline.Workspace)/drop/src/azure.datafactory/ArmTemplate/ARMTemplateForFactory.json'
                csmParametersFile: '$(Pipeline.Workspace)/drop/src/azure.datafactory/ArmTemplate/ARMTemplateForFactory-${{ parameters.environment }}.json'
                deploymentMode: Incremental


            # Start Triggers
            - checkout: self
              displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

            - task: AzurePowerShell@5
              displayName: "Start Data Factory Trigger(s)"
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                azurePowerShellVersion: LatestVersion
                ScriptType: 'InlineScript'
                Inline: |
                  $(System.DefaultWorkingDirectory)/${{ parameters.filePath }} ${{ parameters.deploymentParameters }}