parameters:
  - name: deploymentName
    default: ""
  - name: serviceConnection
    default: ""
  - name: filePath
    default: ""
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: dependsOn
    type: object
    default: []
  - name: displayName
    default: ""
  - name: deploymentParameters
    default: ""


jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: ${{parameters.displayName}}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: "ubuntu-latest" # Ubuntu only!
    variables:
      #- group: ${{ parameters.environment }}
      - group: ${{ parameters.environmentVariableGroup }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: 'Get databricks token'
              inputs:
                azureSubscription: "${{ parameters.serviceConnection }}"
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az --version
                  echo "Getting access token..."
                  DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" -o tsv)
                  echo "##vso[task.setvariable variable=DATABRICKS_TOKEN]$DATABRICKS_TOKEN"

            - checkout: self
              displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

            - task: PowerShell@2
              displayName: 'Deploy Databricks ps1'
              inputs:
                targetType: 'inline'
                script: |
                 $(System.DefaultWorkingDirectory)/${{ parameters.filePath }} ${{ parameters.deploymentParameters }}