parameters:
  - name: deploymentName
    default: ""
  - name: serviceConnection
    default: ""
  - name: folderPath
    default: ""
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: dependsOn
    type: object
    default: []
  - name: displayName
    default: ""
  - name: resourceGroupName
    default: ""
  - name: datafactoryName
    default: ""

jobs:
- job: BuildArtifacts
  pool:
    vmImage: "windows-latest"
  variables:
    - group: ${{ parameters.environmentVariableGroup }}
  steps:
  - task: Npm@1
    displayName: 'Install npm package'
    inputs:
      command: 'install'
      workingDir: '$(Build.Repository.LocalPath)\${{ parameters.folderPath }}'
      verbose: true

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(Build.Repository.LocalPath)\${{ parameters.folderPath }}'
      customCommand: 'run build export $(Build.Repository.LocalPath)\${{ parameters.folderPath }} /subscriptions/$(subscription_id)/resourceGroups/${{ parameters.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ parameters.datafactoryName }} "ArmTemplate"'
    displayName: 'Generate ARM template DataFactory' 

  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.ArtifactStagingDirectory)' 
    displayName: 'Copy Application Artifacts' 

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.Repository.LocalPath)\${{ parameters.folderPath }}\config'
      contents: '*.json'
      targetFolder: '$(Build.ArtifactStagingDirectory)\${{ parameters.folderPath }}\ARMTemplate'
    displayName: 'Copy Template Parameters'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Files'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: drop