trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/azure.datafactory/*
stages: 
  - template: ../../src/environments.yml
    parameters:
      skipBuild: false
      buildTemplatePath:  azure.datafactory/build.yml
      deployTemplatePath: azure.datafactory/deploy.yml