parameters:
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: agentPool
    default: ""
  - name: serviceConnection
    default: ""
  - name: deploymentParameters
    default: ""

jobs:
# Deploy Azure Datafactory   
  - template: ../../core/yaml/datafactory-deploy.yml
    parameters:
      displayName: "Deploy DataFactory Artifacts"
      deploymentName: "DeployDataFactoryArtifacts"
      dependsOn: []
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      folderPath: "src/azure.datafactory/app"
      dataFactoryName: "$(datafactory_name)"
      resourceGroupName: "$(resourceGroup_name)"



  - template: ../../core/yaml/powershell-deploy.yml
    parameters:
      displayName: "Deploy DataFactory Artifacts"
      deploymentName: "DeployDataFactoryArtifacts"
      dependsOn: []
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.serviceConnection }}"
      environmentVariableGroup: "${{ parameters.environmentVariableGroup }}"
      filePath: "core/powershell/datafactory/datafactory.ps1"
      dataFactoryName: "$(datafactory_name)"
      resourceGroupName: "$(resourceGroup_name)"      
      deploymentParameters:
        -Environment "${{ parameters.environment }}"
        -DataFactoryName "$(datafactory_name)"
        -ResourceGroupName "$(resourceGroup_name)"
        -triggerStatus "$(datafactoryTriggers_status)"